version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    expose:
      - 4173
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    expose:
      - 8888
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
